### ISSUE TITLE
Add file diffing

### ISSUE THREAD

**Issue by sim642** [sim642/shy#14]

**Comment by sim642** [comment]
Potential libraries:
- https://code.google.com/archive/p/google-diff-match-patch/ (with patch)
- https://code.google.com/archive/p/java-diff-utils/ (with patch)
  - http://www.adictosaltrabajo.com/tutoriales/comparar-ficheros-java-diff-utils/ (tutorial)

**Comment by Oja95** [comment]
https://github.com/fusesource/jansi for colorized output in Windows

**Comment by sim642** [comment]
Closed by 9875d7e0e56e02094e7a2e35737e38bd154238e5.
